___

**Pandas**
Pandas is a software library written for the Python programming language for data manipulation and analysis. 

It is assumed that Pandas library is alredy install in your system
Exercise
https://pandas.pydata.org/
___

# SF Salaries Exercise - Solutions

Welcome to a quick exercise for you to practice your pandas knowledge. Dataset used [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries). Just follow along and complete the tasks outlined in bold below.

** Import pandas as pd.**

In [79]:
import pandas as pd

** Read Salaries.csv as a dataframe called sal.** 

If you are using CoLabs, you may need to check the documentation in how to load a CSV file.

In [80]:
cols = ['TotalPayBenefits', 'OvertimePay', 'BasePay', 'OtherPay', 'Benefits']
na_values={c: ['Not Provided'] for c in cols}
sal = pd.read_csv('Salaries.csv', na_values=na_values)

/var/folders/x8/v0_l4_492z59nt9n8s65c3sw0000gp/T/ipykernel_9875/2061818082.py:3: DtypeWarning: Columns (12: Status) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv('Salaries.csv', na_values=na_values)

** Check the head of the DataFrame. **

In [81]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

** Use the .info() method to find out how many entries there are.**

In [82]:
sal.info()

<class 'pandas.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  str
 2   JobTitle          148654 non-null  str
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  str
 12  Status            38119 non-null   str
dtypes: float64(7), int64(2), str(4)
memory usage: 14.7 MB

**What is the average BasePay ?**

In [83]:
float(sal['BasePay'].mean())

66325.44884048769

** What is the highest amount of OvertimePay in the dataset ? **

In [84]:
float(sal['OvertimePay'].max())

245131.88

** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll). **

In [85]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

** How much does JOSEPH DRISCOLL make (including benefits)? **

In [86]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

** What is the name of highest paid person (including benefits)?**

In [87]:
sal[
    sal['TotalPayBenefits']
    == sal['TotalPayBenefits'].max()
]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

In [88]:
sal[
    sal['TotalPayBenefits']
    == sal['TotalPayBenefits'].max()
]['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: str

** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [89]:
sal[
    sal['TotalPayBenefits']
    == sal['TotalPayBenefits'].min()
]

# Joe Lopez does not receive any pay, and appears to owe money.

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,PT

In [90]:
sal[
    sal['TotalPayBenefits']
    == sal['TotalPayBenefits'].min()
]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: str

** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **

In [91]:
sal.groupby('Year', as_index=False)['BasePay'].mean().round(6)

   Year       BasePay
0  2011  63595.956517
1  2012  65436.406857
2  2013  69630.030216
3  2014  66564.421924

** How many unique job titles are there? **

In [92]:
sal['JobTitle'].nunique()

2159

** What are the top 5 most common jobs? **

In [93]:
sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **

In [94]:
int((sal[sal['Year'] == 2013]['JobTitle'].value_counts() == 1).sum())

202

** How many people have the word Chief in their job title? (This is pretty tricky) **

In [95]:
sal[sal['JobTitle'].str.contains('Chief', case=False)]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
138011,138012,Sharon C Jackson,Chief Deputy Adlt Probation Of,56660.18,0.00,0.00,566.61,56660.18,57226.79,2014,NaN,San Francisco,PT
139620,139621,Anita S Lee,Chief Clerk,38598.86,0.00,0.00,386.00,38598.86,38984.86,2014,NaN,San Francisco,PT
139709,139710,George D Vaughan,Chief Nursery Specialist,27319.47,483.90,0.00,10334.67,27803.37,38138.04,2014,NaN,San Francisco,PT
140080,140081,Patrick W Gillespie,Chief Preparator,24091.00,0.00,0.00,10176.77,24091.00,34267.77,2014,NaN,San Francisco,PT
140156,140157,Christopher L Ochoa,Chief Stationary Engineer,24392.00,418.71,0.00,8918.44,24810.71,33729.15,2014,NaN,San Francisco,PT

In [ ]:
# This answer reproduces differently, but I think it is correct for this dataset.
int(sal['JobTitle'].str.contains('Chief', case=False).sum())

627

** Optional: Is there a correlation between length of the Job Title string and Salary? **

In [97]:
sal['title_len'] = sal['JobTitle'].str.len()

In [98]:
sal[['title_len', 'TotalPayBenefits']].corr().round(6)

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000